# Generated by Django 6.0 on 2025-12-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('place', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, upload_to='persons/')),
            ],
        ),
    ]
